version: '3'

services:
 
#  vuejswebapp:
#    build: usermap/.
#    depends_on:
#      - smstest
#    ports:
#      - "8080:8080"
#    environment:
#      - GOOGLE_MAP_KEY:"${GOOGLE_MAP_KEY}"
#    volumes:
#      - ./usermap:/usr/src/app
#    networks:
#      - kennet

  smstest:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_MAP_KEY:"${GOOGLE_MAP_KEY}"
      - MONGODB_URI:"mongodb://mongodb:27017/test"
    volumes:
      - ./usermap/dist:/app/usermap/dist
      - ./dist:/app/dist
      - ./src:/app/src
    networks:
      - kennet
    restart: always

  # https://medium.com/better-programming/persistent-databases-using-dockers-volumes-and-mongodb-9ac284c25b39
  mongodb:
    container_name: mongo
    image: mongo:4.4.3
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - kennet

networks:
  kennet:
    driver: bridge
